apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-quarkus
  namespace: redis
  labels:
    app: my-quarkus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-quarkus
  template:
    metadata:
      labels:
        app: my-quarkus
    spec:
      containers:
        - name: my-quarkus
          image: danilo1337/quarkus-and-redis:latest
          env:
            - name: REDIS_IP
              value: my-redis
              #value: my-redis.redis.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-quarkus
  namespace: redis
spec:
  type: ClusterIP
  selector:
    app: my-quarkus
  ports:
    - name: http
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-quarkus
  namespace: redis
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /my-quarkus(/.*|)
          pathType: ImplementationSpecific
          backend:
            service:
              name: my-quarkus
              port:
                number: 8080
