apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-quarkus
  namespace: development
  labels:
    app: app-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-quarkus
  template:
    metadata:
      labels:
        app: app-quarkus
    spec:
      containers:
        - name: app-quarkus
          image: danilo1337/app-quarkus:latest
          env:
            - name: TESTE
              value: VALUE_TESTE
          ports:
          - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: app-quarkus/q/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: app-quarkus
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: app-quarkus
  ports:
    - port: 8080
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-quarkus
  namespace: development
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: ""
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /app-quarkus
            pathType: Prefix
            backend:
              service:
                name: app-quarkus
                port:
                  number: 8080
          - path: /app-quarkus/q
            pathType: Prefix
            backend:
              service:
                name: app-quarkus
                port:
                  number: 8080
